name: Labeler
on:
  pull_request:
    branches:
      - this-branch-to-stop-workflow
jobs:
  labeling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done
      - uses: lykahb/paths-filter@v2
        id: filter
        with:
          stat: json
          filters: |
            changed:
              - '**'
      - name: Remove Label
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: single-line-change-in-contributors-md-file
      - name: Add Label
        id: file-label
        uses: actions-ecosystem/action-add-labels@v1
        if: ${{fromJson(steps.filter.outputs.stat).changed.additionCount == 1 && fromJson(steps.filter.outputs.stat).changed.deletionCount == 0 && steps.changed-files.outputs.all_changed_files == 'Contributors.md' || fromJson(steps.filter.outputs.stat).changed.additionCount == 2 && fromJson(steps.filter.outputs.stat).changed.deletionCount == 1 && steps.changed-files.outputs.all_changed_files == 'Contributors.md' }}
        with:
          labels: single-line-change-in-contributors-md-file

